### ISSUE TITLE
getPlaylist method doesnt give all tracks in playlist

### ISSUE THREAD

**Issue by DaliborTrampota** [DevSnowflake/soundcloud-scraper#11]
After calling a getPlaylist method and providing it this playlist https://soundcloud.com/billieeilish/sets/cry for testing purposes. tracks array property contains only 4 songs but trackCount property gives 18. And the songs are available in my country (czech republic) or atleast more that 4. 

When trying to get this playlist https://soundcloud.com/scumgang6ix9ine/sets/day69-2

I get this error 
```
(node:19596) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'url' of undefined
    at E:\GitHub\DiscordBots\Filter Music Bot\node_modules\soundcloud-scraper\src\Client.js:223:68
    at Array.map (<anonymous>)
    at E:\GitHub\DiscordBots\Filter Music Bot\node_modules\soundcloud-scraper\src\Client.js:197:35
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

these are my functions for loading the playlist but its not really related to the error
```js
function addSoundcloudPlaylist(url, sQueue){
    return new Promise((resolve, reject) => {
        let playlist = [];
        SoundCloud.getPlaylist(url).then(res => {
            console.log(res.tracks.length, res.trackCount)
            for(let track of res.tracks){
                searchTitle(track.title).then(title => {
                    sQueue.addTitle(title)
                    playlist.push(title)
                })
            }
            resolve(true)
        }).catch(err => {
            console.log('here')
            reject(err);
        });
    });
}

function addSoundCloudTrack(url, sQueue){
    return new Promise((resolve, reject) => {
        SoundCloud.getSongInfo(url).then(song => {
            searchTitle(song.title).then(title => {
                sQueue.addTitle(title)
                resolve(title)
            }).catch(reject)
        }).catch(reject)
    })
}
```

**Comment by DaliborTrampota** [comment]
https://soundcloud.com/slowed-and-reverb-songs/sets/sad-slowed-and-reverb-songs this one gives only 5 songs but trackCount says 228

**Comment by twlite** [comment]
@DaliborTrampota yeah, this library does not use soundcloud api to get playlist. It means it only returns the tracks that are available inside page metadata

**Comment by DaliborTrampota** [comment]
> @DaliborTrampota yeah, this library does not use soundcloud api to get playlist. It means it only returns the tracks that are available inside page metadata

Ok and what is the api key in constructor for then? And is there a workaround?

**Comment by twlite** [comment]
@DaliborTrampota That's for audio downloader.

**Comment by DaliborTrampota** [comment]
So there is no way to get atleast 50 of the songs in the playlist?

**Comment by twlite** [comment]
Not currently possible with this library.

**Comment by twlite** [comment]
Closing due to inactivity. Might re-open in the future
